version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel_crud_3tmt
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: LxBbywzjF9y55tkiwJyOkbOPMTv2voH9
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
